// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Categorium struct {
	ID     sql.NullInt32 `json:"id"`
	Nombre string        `json:"nombre"`
}

type Direccion struct {
	ID                sql.NullInt32  `json:"id"`
	Latitud           string         `json:"latitud"`
	Longitud          string         `json:"longitud"`
	DireccionRelativa sql.NullString `json:"direccion_relativa"`
}

type Reporte struct {
	ID          sql.NullInt32  `json:"id"`
	Titulo      string         `json:"titulo"`
	Descripcion sql.NullString `json:"descripcion"`
	Imagen      sql.NullString `json:"imagen"`
	Estado      string         `json:"estado"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UsuarioID   int32          `json:"usuario_id"`
	CategoriaID int32          `json:"categoria_id"`
	DireccionID int32          `json:"direccion_id"`
}

type Usuario struct {
	ID     sql.NullInt32 `json:"id"`
	Nombre string        `json:"nombre"`
}
