// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createReporte = `-- name: CreateReporte :one
INSERT INTO reporte (titulo, descripcion, imagen, estado, usuario_id, categoria_id, direccion_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateReporteParams struct {
	Titulo      string         `json:"titulo"`
	Descripcion sql.NullString `json:"descripcion"`
	Imagen      sql.NullString `json:"imagen"`
	Estado      interface{}    `json:"estado"`
	UsuarioID   int32          `json:"usuario_id"`
	CategoriaID int32          `json:"categoria_id"`
	DireccionID int32          `json:"direccion_id"`
}

func (q *Queries) CreateReporte(ctx context.Context, arg CreateReporteParams) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, createReporte,
		arg.Titulo,
		arg.Descripcion,
		arg.Imagen,
		arg.Estado,
		arg.UsuarioID,
		arg.CategoriaID,
		arg.DireccionID,
	)
	var id sql.NullInt32
	err := row.Scan(&id)
	return id, err
}

const deleteReporte = `-- name: DeleteReporte :exec
DELETE FROM reporte
WHERE id = $1
`

func (q *Queries) DeleteReporte(ctx context.Context, id sql.NullInt32) error {
	_, err := q.db.ExecContext(ctx, deleteReporte, id)
	return err
}

const getReporte = `-- name: GetReporte :one
SELECT id, titulo, descripcion, imagen, estado, created_at, updated_at, deleted_at, usuario_id, categoria_id, direccion_id
FROM reporte
WHERE id = $1
`

func (q *Queries) GetReporte(ctx context.Context, id sql.NullInt32) (Reporte, error) {
	row := q.db.QueryRowContext(ctx, getReporte, id)
	var i Reporte
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Imagen,
		&i.Estado,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UsuarioID,
		&i.CategoriaID,
		&i.DireccionID,
	)
	return i, err
}

const listReportes = `-- name: ListReportes :many
SELECT id, titulo, descripcion, imagen, estado, created_at, updated_at, deleted_at, usuario_id, categoria_id, direccion_id
FROM reporte
ORDER BY id
`

func (q *Queries) ListReportes(ctx context.Context) ([]Reporte, error) {
	rows, err := q.db.QueryContext(ctx, listReportes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reporte
	for rows.Next() {
		var i Reporte
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Imagen,
			&i.Estado,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UsuarioID,
			&i.CategoriaID,
			&i.DireccionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEstadoReporte = `-- name: UpdateEstadoReporte :exec
UPDATE reporte
SET estado = $2 WHERE id = $1
`

type UpdateEstadoReporteParams struct {
	ID     sql.NullInt32 `json:"id"`
	Estado interface{}   `json:"estado"`
}

func (q *Queries) UpdateEstadoReporte(ctx context.Context, arg UpdateEstadoReporteParams) error {
	_, err := q.db.ExecContext(ctx, updateEstadoReporte, arg.ID, arg.Estado)
	return err
}
